# Generated by Django 6.0.1 on 2026-02-12 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='percentage_cut',
            field=models.DecimalField(decimal_places=2, default=4.0, max_digits=5),
        ),
    ]
